# Generated by Django 5.0.7 on 2024-08-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_customer_image_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
