# Generated by Django 5.0.7 on 2024-09-01 11:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='cart_id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
